[unix_http_server]
file=/tmp/supervisor.sock
chmod=0777
chown=appuser:appuser

[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
user=appuser

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:php-fpm]
command=php-fpm -F -R
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker-high]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend/artisan queue:work rabbitmq --queue=high --sleep=3 --tries=3 --timeout=60
autostart=true
autorestart=true
user=appuser
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/backend/storage/logs/worker-high.log
stderr_logfile=/var/www/backend/storage/logs/worker-high-error.log
stopwaitsecs=3600
directory=/var/www/backend
environment=HOME=/home/appuser,USER=appuser,QUEUE_CONNECTION=rabbitmq,RABBITMQ_HOST=rabbitmq,RABBITMQ_PORT=5672,RABBITMQ_USER=guest,RABBITMQ_PASSWORD=guest,RABBITMQ_VHOST=/

[program:laravel-worker-low]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend/artisan queue:work rabbitmq --queue=low --sleep=3 --tries=3 --timeout=60
autostart=true
autorestart=true
user=appuser
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/backend/storage/logs/worker-low.log
stderr_logfile=/var/www/backend/storage/logs/worker-low-error.log
stopwaitsecs=3600
directory=/var/www/backend
environment=HOME=/home/appuser,USER=appuser,QUEUE_CONNECTION=rabbitmq,RABBITMQ_HOST=rabbitmq,RABBITMQ_PORT=5672,RABBITMQ_USER=guest,RABBITMQ_PASSWORD=guest,RABBITMQ_VHOST=/

[program:health-check]
command=bash -c "while true; do php /var/www/backend/artisan health:check; sleep 60; done"
autostart=true
autorestart=true
user=appuser
redirect_stderr=true
stdout_logfile=/var/www/backend/storage/logs/health-check.log
stderr_logfile=/var/www/backend/storage/logs/health-check-error.log